name: visao_360
description: "Um aplicativo para visualização de lentes ópticas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.0
  flutter_svg: ^2.0.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.11

# ===== SPLASH SCREEN CONFIG =====
flutter_native_splash:
  color: "#FFFFFF"
  background_image: "assets/splash/background.png"
  android: true
  ios: true
  web: false
  fullscreen: true

# ===== LAUNCHER ICONS CONFIG =====
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

# ===== FLUTTER CONFIG =====
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/splash/  # ← ADD THIS LINE FOR SPLASH SCREEN IMAGE
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700