name: lentes_app
description: "Um aplicativo para visualização de lentes ópticas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2

  # PDF e impressão
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.3

  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.0

  flutter_svg: ^2.0.10

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
